FROM python:3.8-slim-buster as gdown

RUN pip install gdown
WORKDIR /
RUN gdown "https://drive.google.com/u/0/uc?id=1OdGgvInnj8Q7IxchF8b3iWoXrb72uEjx&export=download" -O ClusterBlast.zip


FROM alpine/git as git

WORKDIR /

RUN git clone https://github.com/victoriapascal/gutsmash.git && \
    (find gutsmash/antismash/ -type f | xargs chmod go+rw) && \
    (find gutsmash/antismash/ -name "*.py" | xargs chmod go+x) && \
    (find gutsmash/antismash/ -type d | xargs chmod go+rwx)

RUN wget https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz
RUN gunzip Pfam-A.hmm.gz
RUN mv Pfam-A.hmm gutsmash/antismash/databases/Pfam-A.hmm

RUN wget https://gutsmash.bioinformatics.nl/static/databases_to_share/resfam.zip
RUN unzip resfam.zip
RUN mv resfam gutsmash/antismash/databases/resfam

COPY --from=gdown /ClusterBlast.zip /ClusterBlast.zip
RUN unzip ClusterBlast.zip -d ClusterBlast
RUN mv ClusterBlast gutsmash/antismash/databases/ClusterBlast


FROM mambaorg/micromamba:1.1.0

USER $MAMBA_USER
ARG MAMBA_DOCKERFILE_ACTIVATE=1
COPY --chown=$MAMBA_USER:$MAMBA_USER docker/env.yaml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes

COPY --from=git /gutsmash /usr/share/gutsmash

RUN echo "alias gutsmash='python /usr/share/gutsmash/run_gutsmash.py'" >> ~/.bashrc